### ISSUE TITLE
Class not found error on installation to clean 5.7.5.3

### ISSUE THREAD

**Issue by katalysis** [concrete5/addon_migration_tool#3]
Installing the package on a clean 5.7.5.3 gives the following error:

An unexpected error occurred.
Class 'Concrete\Core\Backup\ContentImporter\ValueInspector\InspectionRoutine\PageRoutine' not found

The package then appears partially installed but there is no interface.

**Comment by aembler** [comment]
This shouldn't be installed on 5.7.5.3. We need to update the version. For the foreseeable future you should be installing the package on the most recent develop branch from GitHub.
