### ISSUE TITLE
Export & Import scrapbook proxy blocks

### ISSUE THREAD

**Issue by hissy** [concrete5/addon_migration_tool#30]
Is there any good way to export or import scrapbook proxy block instances?

**Comment by aembler** [comment]
In the current 8.2 develop branch of version 8 and the latest branch of 5.6
we've solved this by simply exporting the original block in the instance of
using a scrapbook. Much easier and cleaner that way. With this code
installed you should never see a "core_scrapbook_block" come in through the
exporter, since the original block is used instead.

**Comment by hissy** [comment]
@aembler Thank you for your information. I had done migration with 8.2.0a2 but it was not solved. Please tell me when you fixed this issue!

**Comment by biplobice** [comment]
@aembler Thank you for this fix. As @hissy said, we already have exported and imported scrapbook proxy blocks. And after that we inserted lots of data into our website. But, recently we've found that our scrapbook proxy blocks are missing. In this situation, what's the best way you think to get back those blocks?

**Comment by aembler** [comment]
Unfortunately I think you might be out of luck on that one.

**Comment by hissy** [comment]
> In the current 8.2 develop branch of version 8 and the latest branch of 5.6
we've solved this by simply exporting the original block in the instance of
using a scrapbook.

Sorry, but I can't find this code.

**Comment by aembler** [comment]
You shouldn't have to find anything – if you use 5.6.3.5 to export your
site, it will not export scrapbook proxy blocks. Instead it will export an
instance of the original block.

On Thu, Jun 15, 2017 at 11:15 PM, Takuro Hishikawa <notifications@github.com

**Comment by hissy** [comment]
Oh, I found it in the core. thanks!
https://github.com/concrete5/concrete5-legacy/commit/6b36b1b38912259442d50b3847a9fc4674d912f0
