### ISSUE TITLE
C5.8.2.1 import error 'This does not appear to be a valid concrete5 mapping file'

### ISSUE THREAD

**Issue by sciascia** [concrete5/addon_migration_tool#37]
Great tool BTW but C5.8 won't import from a c5.6.3.5b1 export - get error 'This does not appear to be a valid concrete5 mapping file'

The start of the 5.6 export.xml file looks correct but I'm not 100% sure...
````
<?xml version="1.0" encoding="UTF-8"?>
<concrete5-cif version="1.0"><pages><page name="Sheets" path="/shop/sheets" filename="" public-date="2014-04-18 13:20:00"
````

Has anyone else seen this? 

Cheers

**Comment by dgreer234** [comment]
Yes, I just got this error trying to migrate from c5.6.3.5 to c5.8.3.2

**Comment by aembler** [comment]
You’re not adding the file in the right place. You don’t add the file in the opening dialog where you create the batch. You add it in the next page where you click the “add content” button.
