### ISSUE TITLE
Errors when using migration tool with 8.2.1

### ISSUE THREAD

**Issue by janwidmer** [concrete5/addon_migration_tool#43]
Hi There,

I am trying to migrate between to servers, both having concrete version 8.2.1. I added my content to the export batch. That worked so far, besides for Page Types.

Reproduce:

1.  Click on Add Content to Batch
2. Choose "Page Types" in Dropdown and click "go"
3. I get the Exception

`Call to a member function isDefault() on null` within the method

```
public function getResultColumns(ExportItem $exportItem)
    {
        $t = \Concrete\Core\Page\Type\Type::getByID($exportItem->getItemIdentifier());
        if (is_object($t)) {
            if (method_exists($t, 'getSiteTypeObject')) {
                $siteType = $t->getSiteTypeObject();
                if (!$siteType->isDefault()) {
                    return array($siteType->getSiteTypeName() . ': ' . $t->getPageTypeDisplayName());
                }
            }
 
            return array($t->getPageTypeDisplayName());
        }
 
        return array();
    }
```

When I leave Page Types away and just try to export the Rest of the Content, I get the following error after hitting "Export Batch

`Call to a member function loadController() on null` within the method

```
public static function getByID($btID)
    {
        $em = \ORM::entityManager();
        $bt = $em->getRepository('\Concrete\Core\Entity\Block\BlockType\BlockType')->find($btID);
        $bt->loadController();
 
        return $bt;
    }
```

Any idea? Is migration FROM 8.2.1 not supported?

**Comment by aembler** [comment]
Migrating from 8.2.1 should definitely be supported. Is this an upgrade from a previous version? It sounds like not all the data in the various tables is correctly populated.

**Comment by janwidmer** [comment]
Yes it was an upgrad from the earliest of the "new world" versions.. I just installed a fresh 8.2.1 version and will try the migration tool again here.

**Comment by janwidmer** [comment]
ok, with a fresh instance of C5 8.2.1 it worked.
