### ISSUE TITLE
Call to undefined method PortlandLabs\Concrete5\MigrationTool\Entity\Import\BlockValue\ImportedBlockValue::getAreaLayout()

### ISSUE THREAD

**Issue by martbase** [concrete5/addon_migration_tool#45]
When adding content to an import batch the following exception is raised

Call to undefined method PortlandLabs\Concrete5\MigrationTool\Entity\Import\BlockValue\ImportedBlockValue::getAreaLayout() in file \packages\migration_tool\src\PortlandLabs\Concrete5\MigrationTool\Batch\ContentMapper\Type\BlockType.php","line":44

```
$columns = $block->getBlockValue()->getAreaLayout()->getColumns();
```
Using concrete5 ver 8.2.1 and migration_tool ver 0.8.0

**Comment by GutDing** [comment]
I got the same error with block type="**core_area_layout**".
In Line 44 the classname of $block->getBlockValue() is ImportedBlockValue and has no method getAreaLayout().

The cause was loading an "unmapped"-driver for all block types.
fix in #48
