### ISSUE TITLE
There should be a release for Concrete 5.7.x - appVersionRequired updated to 8.x.x

### ISSUE THREAD

**Issue by martbase** [concrete5/addon_migration_tool#55]
There are situations where one would like to migrate a 5.7 site to 5.8 without performing an in-place upgrade for example when moving a site between different hosts.

It will be very convenient to have the latest branch that supported 5.7.x available under **Releases**

**Comment by bikerdave** [comment]
+1

Looks like this commit was the last where 5.7.x was supported: https://github.com/concrete5/addon_migration_tool/tree/82cf6c10d81f01c2ac7c4ed04d1bb460a573e9b5

**Comment by aembler** [comment]
👍 https://github.com/concrete5/addon_migration_tool/releases
