### ISSUE TITLE
Internal links stay empty after import

### ISSUE THREAD

**Issue by c5dragon** [concrete5/addon_migration_tool#65]
When trying to migrate the content of 5.6 to v8.4, internal links in the content blocks stay empty. The internal linked files are correctly linked.

XML File:
`<a href="{ccm:export:page:/faq/categorie/questionanswer}" title="Link title">Link</a>` 

After import:
`<a title="Link title" href="">Link</a>`

Is there anyway to save the paths? Guess the pages are not linked because they don't exist yet.

**Comment by aembler** [comment]
Those pages must be included in the import batch or already exist in the site otherwise there will be no way for the migration tool to link them.

**Comment by c5dragon** [comment]
As far as I know all the pages are included in the same batch.
Sitetree:
```
FAQ
- Categories
-- questionanswer
- Categories
-- questionanswer
```
And that''s what I'm exporting.
