### ISSUE TITLE
Parent Page Handle

### ISSUE THREAD

**Issue by JeffPaetkau** [concrete5/addon_migration_tool#73]
There is a bug in src/PortlandLabs/Concrete5/MigrationTool/Publisher/Routine/AbstractPageAction.php line 69

`$data['handle'] = $path;`

should be

`$data['cHandle'] = $path;`

This section of code creates placeholder parent pages if they don't exist as part of the import. Most of the time it works fine because it auto-creates a slug/handle based on the page name. However, my use case is importing from WP. Slight variations in how WP and C5 generate slugs means that on occasion this generates a page that doesn't match the actual parent path of the page being imported. Other code tries to lookup the created parent based on the path but returns null because the paths don't match.

I spent 8 hours of my life tracking down this stupid bug yesterday :(

**Comment by JeffPaetkau** [comment]
On the upside I now have a much better understanding of how the migration tool is built :)

**Comment by aembler** [comment]
Would you consider adding a pull request for this? Sounds like it'd be pretty easy and would be a nice fix; I'm not sure when we're going to be able to get back to the migration tool for awhile.

**Comment by wordish** [comment]
This seems to have been fixed in #80
