### ISSUE TITLE
Images in content areas are not mapped to imported files

### ISSUE THREAD

**Issue by dbuonomo** [concrete5/addon_migration_tool#78]
I am migrating a site from 5.6.4.0 to 8.3.1 using the migration tools. Images that are embedded in a content block are not mapped to imported files (in my case only jpg and png image files). I've uploaded the images both before and after the XML import file, re-scanned the batch, and verified that the files are in the File Manager.

I have also verified that the filename is the same, and I can see the key and filename reference in the .xml doc. This does not appear to be an issue with spaces in the filename.

**Comment by dbuonomo** [comment]
Not sure this is helpful, but in my case, all of the images that are flagged as not found have ether a hyphen or underscore in the filename.

**Comment by dbuonomo** [comment]
I found a temporary fix by removing the ID associated with image references in the export XML file. As an example, changing this:

... <img src="{ccm:export:image:421428972581:myfile.jpg}" ...

to this:

... <img src="{ccm:export:image:myfile.jpg}" ...

resulted in a successful match to the file in the File Manager.

I used this regex in a search/replace to change all occurrences of this pattern:

ccm:export:image:[0-9]*:

**Comment by stephenr85** [comment]
This is due to the prefixes not being accounted for in the core's ImageRoutine. I have submitted a pull request.
https://github.com/concrete5/concrete5/pull/8151
